### ISSUE TITLE
Pre-release refactoring

### ISSUE THREAD

**Issue by aydoganersoz** [aydoganersoz/tomat#39]

**Comment by aydoganersoz** [comment]
@ivajloip @moutoum I'd be glad if you review my small application and tell me anything you want (recommendations, etc). You can comment on the architecture as well as code quality so that I can improve myself :slightly_smiling_face:

**Comment by ivajloip** [comment]
Hi Aydu,

This looks like a fun project :slightly_smiling_face: Here are my thoughts. I think it is mostly good and looks mostly idiomatic Rust (not that I am any expert, mind you). That being said, here are some questions and recommendations.

I am not sure I managed to understand how exactly the program is supposed to be used - so you start it from somewhere and it will create a db folder with your database file inside. If that is the case, maybe your database could be in the home folder ($HOME/.local for example). 

I am not sure what does [set_timer timer.rs#L20][1] is supposed to do. Generally when you pass a bool you should ask yourself - do I need two functions with possibly a helper function that does some of the work. In your case I would suppose that you can just provide a Duration :slightly_smiling_face: 

In this function also, while there is nothing wrong with using match with a boolean, I would expect to see an `if` statement at that place.

My last thought is that I prefer to have an object with a fixed interface that models the storage. The other part of your program can only rely on the abstraction. The nice things is that then if you want to support switching between json file and sqlite db, your main program can create a different type of storage depending on your parameters. 

Let me know if you need more discussion :slightly_smiling_face: 

[1]: https://github.com/aydoganersoz/tomat/blob/master/src/timer.rs#L20

**Comment by aydoganersoz** [comment]
Hi Ivo,

Thanks a lot for your feedback that is really beneficial. I tried to apply some them already and for the rest I keep them in mind :slightly_smiling_face: 

Cheers
